name: qd-suite
channels:
  - conda-forge
dependencies:
  - python=3.11
  - fastapi
  - uvicorn
  - pydantic
  - pyyaml
  - ase
  - pip
  - pip:
      - schema==0.7.4
      - git+https://github.com/nlesc-nano/miniCAT
      - git+https://github.com/nlesc-nano/QD_Builder

