charges:
  In: 3
  Sb: -3
  Cl: -1
passivation:
  ligand: Cl
  surf_tol: 2.0
  prepass_mode: role-aware
  prepass_min_cn_terrace: 3
  prepass_min_cn_edge: 2
  prepass_min_cn_vertex: 1
facets:
- hkl: '100'
  scope: family
  termination: cation_rich
  gamma: 1.2
- hkl: '111'
  scope: family
  termination: cation_rich
  gamma: 0.8
- hkl: -1-1-1
  scope: family
  termination: anion_rich
  gamma: 1.6
symmetry:
  proper_rotations_only: true
size_unit_cells:
- 1.5
- 1.5
- 1.5
construction_origin:
  center_on_species: Sb
