name: Deploy Docs to GitHub Pages

on:
  push:
    branches: [main]
    # optional – only redeploy when the docs change
    paths:
      - 'docs/**'
  schedule:
    - cron:  '0 0 * * 0'   # Sunday 00:00 UTC
  workflow_dispatch:

permissions:
  contents: read
  pages:     write
  id-token:  write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # if you have a Sphinx / MkDocs / Vite build, do it here
      # - run: mkdocs build -d docs

      - name: Package site
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs            # whatever directory has index.html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4


